import EventEmitter from "events";

export const myEmitter = new EventEmitter();

export const EventName = {
	PRODUCT_GOT_EXPIRED: "PRODUCT_GOT_EXPIRED",
	PRODUCT_ADDED_TO_WISHLIST: "PRODUCT_ADDED_TO_WISHLIST",
	PRODUCT_REMOVED_FROM_WISHLIST: "PRODUCT_REMOVED_FROM_WISHLIST",
	PRRODUCT_BOUGHT: "PRODUCT_BOUGHT",
	ORDER_PENDING: "ORDER_PENDING",
	ORDERS_DELIVERED: "ORDERS_DELIVERED",
	ORDERS_CANCELED: "ORDERS_CANCELED",
};
