# This workflow will install node dependencies, run tests and report coverage
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: build

on:
  push:
    branches:
      - feat-test-CI-implementation-187419042
      - "*"
      - develop

  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DB_TEST_URL: ${{ secrets.DB_TEST_URL }}
      DEV_MODE: ${{ secrets.DEV_MODE }}
      DB_HOSTED_MODE: ${{ secrets.DB_HOSTED_MODE }}

    strategy:
      matrix:
        node-version: ["20.x"]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Install dependencies
        run: npm install

      - name: Run tests and build test coverage
        run: npm run test:ci

      - name: Test & publish code climate coverage
        uses: paambaati/codeclimate-action@v5.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: npm run test:ci
          debug: true
          coverageLocations: |
            ${{github.workspace}}/*.lcov:lcov
